# Generated by Django 2.2.4 on 2019-08-29 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20190829_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent',
            new_name='parents',
        ),
    ]
